apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: nginx-container
    image: cassette1122/my-private-repo
    env:
    - name: APP_PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_PORT
    - name: APP_URL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_URL
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: secret-basic-auth
