---
- name: Install nginx on Ubuntu
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install httpd on Fedora
  dnf:
    name: httpd
    state: present
  when: ansible_distribution == "Fedora"

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: Enable 80 port on Ubuntu
  ufw:
    rule: allow
    port: 80
    proto: tcp
  when: ansible_distribution == "Ubuntu"

- name: Enable 80 port on Fedora
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  when: ansible_distribution == "Fedora"

- name: Start nginx on Ubuntu
  service:
    name: nginx
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Start httpd on Fedora
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"