---
- name: Manage user
  hosts: all
  become: yes
  vars:
    username: ansible_user

  tasks:
    - name: Add user to all groups
      user:
        name: "{{ username }}"
        password: "{{ user_password }}"
        state: present
        shell: /bin/bash
        createhome: yes

    - name: Add user to sudo group
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes
      when: ansible_distribution == "Ubuntu"

    - name: Add user to wheel group
      user:
        name: "{{ username }}"
        groups: wheel
        append: yes
      when: ansible_distribution == "Fedora"