version: '3'

services:
  db:
    build: .
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: abc_123
      POSTGRES_DB: my_db_app
      PGDATA: /var/lib/postgresql/data/mydata
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data/mydata
