---
- name: Gather facts
  hosts: all
  gather_facts: yes  
  tasks:
    - name: Output facts
      debug:
        msg: Дистрибутив - {{ ansible_distribution }}; Версия ОС - {{ ansible_distribution_version }}
